package com.administrator.shopkeepertablet.model.greendao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.administrator.shopkeepertablet.model.entity.ProductKouWeiEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUCT_KOU_WEI_ENTITY".
*/
public class ProductKouWeiEntityDao extends AbstractDao<ProductKouWeiEntity, String> {

    public static final String TABLENAME = "PRODUCT_KOU_WEI_ENTITY";

    /**
     * Properties of entity ProductKouWeiEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property UId = new Property(0, String.class, "uId", true, "U_ID");
        public final static Property No = new Property(1, String.class, "no", false, "NO");
        public final static Property RestaurantId = new Property(2, String.class, "restaurantId", false, "RESTAURANT_ID");
        public final static Property Type = new Property(3, String.class, "type", false, "TYPE");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property ProductId = new Property(5, String.class, "productId", false, "PRODUCT_ID");
        public final static Property Select = new Property(6, boolean.class, "select", false, "SELECT");
    }

    private Query<ProductKouWeiEntity> foodEntity_ProductKouWeiEntityListQuery;

    public ProductKouWeiEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ProductKouWeiEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUCT_KOU_WEI_ENTITY\" (" + //
                "\"U_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: uId
                "\"NO\" TEXT," + // 1: no
                "\"RESTAURANT_ID\" TEXT," + // 2: restaurantId
                "\"TYPE\" TEXT," + // 3: type
                "\"NAME\" TEXT," + // 4: name
                "\"PRODUCT_ID\" TEXT," + // 5: productId
                "\"SELECT\" INTEGER NOT NULL );"); // 6: select
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUCT_KOU_WEI_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProductKouWeiEntity entity) {
        stmt.clearBindings();
 
        String uId = entity.getUId();
        if (uId != null) {
            stmt.bindString(1, uId);
        }
 
        String no = entity.getNo();
        if (no != null) {
            stmt.bindString(2, no);
        }
 
        String restaurantId = entity.getRestaurantId();
        if (restaurantId != null) {
            stmt.bindString(3, restaurantId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String productId = entity.getProductId();
        if (productId != null) {
            stmt.bindString(6, productId);
        }
        stmt.bindLong(7, entity.getSelect() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProductKouWeiEntity entity) {
        stmt.clearBindings();
 
        String uId = entity.getUId();
        if (uId != null) {
            stmt.bindString(1, uId);
        }
 
        String no = entity.getNo();
        if (no != null) {
            stmt.bindString(2, no);
        }
 
        String restaurantId = entity.getRestaurantId();
        if (restaurantId != null) {
            stmt.bindString(3, restaurantId);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(4, type);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String productId = entity.getProductId();
        if (productId != null) {
            stmt.bindString(6, productId);
        }
        stmt.bindLong(7, entity.getSelect() ? 1L: 0L);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ProductKouWeiEntity readEntity(Cursor cursor, int offset) {
        ProductKouWeiEntity entity = new ProductKouWeiEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // uId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // no
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // restaurantId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // type
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // productId
            cursor.getShort(offset + 6) != 0 // select
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProductKouWeiEntity entity, int offset) {
        entity.setUId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRestaurantId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setType(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setProductId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSelect(cursor.getShort(offset + 6) != 0);
     }
    
    @Override
    protected final String updateKeyAfterInsert(ProductKouWeiEntity entity, long rowId) {
        return entity.getUId();
    }
    
    @Override
    public String getKey(ProductKouWeiEntity entity) {
        if(entity != null) {
            return entity.getUId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProductKouWeiEntity entity) {
        return entity.getUId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "productKouWeiEntityList" to-many relationship of FoodEntity. */
    public List<ProductKouWeiEntity> _queryFoodEntity_ProductKouWeiEntityList(String productId) {
        synchronized (this) {
            if (foodEntity_ProductKouWeiEntityListQuery == null) {
                QueryBuilder<ProductKouWeiEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductId.eq(null));
                foodEntity_ProductKouWeiEntityListQuery = queryBuilder.build();
            }
        }
        Query<ProductKouWeiEntity> query = foodEntity_ProductKouWeiEntityListQuery.forCurrentThread();
        query.setParameter(0, productId);
        return query.list();
    }

}
